CREATE TABLE IF NOT EXISTS inf_project (
  project_id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '项目ID',
  project_code varchar(64) NOT NULL COMMENT '项目编号',
  project_name varchar(128) NOT NULL COMMENT '项目名称',
  project_type varchar(32) NOT NULL COMMENT '项目类型',
  project_status varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '项目状态',
  project_phase varchar(32) DEFAULT NULL COMMENT '项目阶段',
  owner_dept_id bigint(20) DEFAULT NULL COMMENT '归属部门ID',
  project_manager varchar(64) DEFAULT NULL COMMENT '项目经理',
  owner_leader varchar(64) DEFAULT NULL COMMENT '业主负责人',
  vendor_name varchar(128) DEFAULT NULL COMMENT '开发单位',
  vendor_owner varchar(64) DEFAULT NULL COMMENT '开发单位负责人',
  portal_owner varchar(64) DEFAULT NULL COMMENT '统一门户负责人',
  resource_owner varchar(64) DEFAULT NULL COMMENT 'IT资源负责人',
  data_owner varchar(64) DEFAULT NULL COMMENT '数据资源负责人',
  security_owner varchar(64) DEFAULT NULL COMMENT '安全负责人',
  target_users varchar(255) DEFAULT NULL COMMENT '目标用户',
  directory_template_json text COMMENT '标准目录模板',
  custom_directory_json text COMMENT '非标准目录模板',
  acceptance_status varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '验收状态',
  plan_start_date datetime DEFAULT NULL COMMENT '计划开始日期',
  plan_end_date datetime DEFAULT NULL COMMENT '计划结束日期',
  create_by varchar(64) DEFAULT '' COMMENT '创建者',
  create_time datetime DEFAULT NULL COMMENT '创建时间',
  update_by varchar(64) DEFAULT '' COMMENT '更新者',
  update_time datetime DEFAULT NULL COMMENT '更新时间',
  remark varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (project_id),
  UNIQUE KEY uk_project_code (project_code),
  KEY idx_project_status (project_status),
  KEY idx_project_type (project_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='信息化项目表';

CREATE TABLE IF NOT EXISTS inf_project_template (
  template_id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '模板ID',
  template_name varchar(128) NOT NULL COMMENT '模板名称',
  project_type varchar(32) NOT NULL COMMENT '项目类型',
  phase_name varchar(64) DEFAULT NULL COMMENT '阶段名称',
  version_no varchar(32) DEFAULT NULL COMMENT '版本号',
  directory_json text COMMENT '目录JSON',
  status varchar(32) NOT NULL DEFAULT '0' COMMENT '状态',
  create_by varchar(64) DEFAULT '' COMMENT '创建者',
  create_time datetime DEFAULT NULL COMMENT '创建时间',
  update_by varchar(64) DEFAULT '' COMMENT '更新者',
  update_time datetime DEFAULT NULL COMMENT '更新时间',
  remark varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (template_id),
  KEY idx_template_type (project_type),
  KEY idx_template_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目模板表';

CREATE TABLE IF NOT EXISTS inf_resource (
  resource_id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '资源ID',
  resource_code varchar(64) NOT NULL COMMENT '资源编号',
  resource_name varchar(128) NOT NULL COMMENT '资源名称',
  resource_type varchar(32) NOT NULL COMMENT '资源类型',
  resource_status varchar(32) NOT NULL DEFAULT 'IDLE' COMMENT '资源状态',
  monitor_status varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '监控状态',
  project_id bigint(20) DEFAULT NULL COMMENT '项目ID',
  owner_dept_id bigint(20) DEFAULT NULL COMMENT '归属部门ID',
  owner_name varchar(64) DEFAULT NULL COMMENT '责任人',
  maintainer_name varchar(64) DEFAULT NULL COMMENT '维护人',
  cpu_cores int(11) DEFAULT NULL COMMENT 'CPU核数',
  memory_gb int(11) DEFAULT NULL COMMENT '内存GB',
  storage_gb int(11) DEFAULT NULL COMMENT '存储GB',
  os_name varchar(64) DEFAULT NULL COMMENT '操作系统',
  ip_address varchar(64) DEFAULT NULL COMMENT 'IP地址',
  software_name varchar(128) DEFAULT NULL COMMENT '软件名称',
  software_version varchar(64) DEFAULT NULL COMMENT '软件版本',
  license_count int(11) DEFAULT NULL COMMENT '许可证数量',
  delivery_time datetime DEFAULT NULL COMMENT '交付时间',
  relation_summary varchar(500) DEFAULT NULL COMMENT '关系摘要',
  performance_summary varchar(500) DEFAULT NULL COMMENT '性能摘要',
  create_by varchar(64) DEFAULT '' COMMENT '创建者',
  create_time datetime DEFAULT NULL COMMENT '创建时间',
  update_by varchar(64) DEFAULT '' COMMENT '更新者',
  update_time datetime DEFAULT NULL COMMENT '更新时间',
  remark varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (resource_id),
  UNIQUE KEY uk_resource_code (resource_code),
  KEY idx_resource_type (resource_type),
  KEY idx_resource_status (resource_status),
  KEY idx_resource_project (project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='IT资源表';

CREATE TABLE IF NOT EXISTS inf_application (
  application_id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '应用ID',
  application_code varchar(64) NOT NULL COMMENT '应用编号',
  application_name varchar(128) NOT NULL COMMENT '应用名称',
  application_type varchar(32) NOT NULL COMMENT '应用类型',
  classification_level varchar(32) DEFAULT NULL COMMENT '分类级别',
  application_status varchar(32) NOT NULL DEFAULT 'BUILDING' COMMENT '应用状态',
  project_id bigint(20) DEFAULT NULL COMMENT '项目ID',
  owner_org varchar(128) DEFAULT NULL COMMENT '业主单位',
  owner_name varchar(64) DEFAULT NULL COMMENT '业主负责人',
  vendor_name varchar(128) DEFAULT NULL COMMENT '开发单位',
  vendor_owner varchar(64) DEFAULT NULL COMMENT '开发负责人',
  portal_owner varchar(64) DEFAULT NULL COMMENT '统一门户负责人',
  resource_owner varchar(64) DEFAULT NULL COMMENT 'IT资源负责人',
  data_owner varchar(64) DEFAULT NULL COMMENT '数据负责人',
  security_owner varchar(64) DEFAULT NULL COMMENT '安全负责人',
  access_url varchar(255) DEFAULT NULL COMMENT '访问地址',
  tech_stack varchar(255) DEFAULT NULL COMMENT '技术栈',
  resource_summary varchar(500) DEFAULT NULL COMMENT '资源摘要',
  network_summary varchar(500) DEFAULT NULL COMMENT '网络摘要',
  relation_summary varchar(500) DEFAULT NULL COMMENT '关系摘要',
  create_by varchar(64) DEFAULT '' COMMENT '创建者',
  create_time datetime DEFAULT NULL COMMENT '创建时间',
  update_by varchar(64) DEFAULT '' COMMENT '更新者',
  update_time datetime DEFAULT NULL COMMENT '更新时间',
  remark varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (application_id),
  UNIQUE KEY uk_application_code (application_code),
  KEY idx_application_status (application_status),
  KEY idx_application_classification (classification_level)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='应用台账表';

CREATE TABLE IF NOT EXISTS inf_data_asset (
  asset_id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '资产ID',
  asset_code varchar(64) NOT NULL COMMENT '资产编号',
  asset_name varchar(128) NOT NULL COMMENT '资产名称',
  business_domain varchar(64) DEFAULT NULL COMMENT '业务域',
  asset_type varchar(32) DEFAULT NULL COMMENT '资产类型',
  asset_status varchar(32) NOT NULL DEFAULT 'DESIGNING' COMMENT '资产状态',
  security_level varchar(32) DEFAULT NULL COMMENT '安全等级',
  source_system varchar(128) DEFAULT NULL COMMENT '来源系统',
  data_format varchar(64) DEFAULT NULL COMMENT '数据格式',
  schema_desc text COMMENT '模式描述',
  dictionary_desc text COMMENT '字典描述',
  update_frequency varchar(32) DEFAULT NULL COMMENT '更新频率',
  data_volume varchar(64) DEFAULT NULL COMMENT '数据量',
  storage_location varchar(255) DEFAULT NULL COMMENT '存储位置',
  share_mode varchar(64) DEFAULT NULL COMMENT '共享方式',
  share_condition varchar(255) DEFAULT NULL COMMENT '共享条件',
  owner_dept_name varchar(128) DEFAULT NULL COMMENT '责任部门',
  owner_name varchar(64) DEFAULT NULL COMMENT '责任人',
  contact_phone varchar(32) DEFAULT NULL COMMENT '联系电话',
  tag_names varchar(255) DEFAULT NULL COMMENT '标签',
  lineage_desc text COMMENT '血缘说明',
  quality_rule_desc text COMMENT '质量规则说明',
  create_by varchar(64) DEFAULT '' COMMENT '创建者',
  create_time datetime DEFAULT NULL COMMENT '创建时间',
  update_by varchar(64) DEFAULT '' COMMENT '更新者',
  update_time datetime DEFAULT NULL COMMENT '更新时间',
  remark varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (asset_id),
  UNIQUE KEY uk_asset_code (asset_code),
  KEY idx_asset_status (asset_status),
  KEY idx_asset_security (security_level),
  KEY idx_asset_domain (business_domain)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据资产表';

CREATE TABLE IF NOT EXISTS inf_data_asset_version (
  version_id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '版本ID',
  asset_id bigint(20) NOT NULL COMMENT '资产ID',
  version_no varchar(32) NOT NULL COMMENT '版本号',
  change_type varchar(32) DEFAULT NULL COMMENT '变更类型',
  snapshot_json longtext COMMENT '快照JSON',
  change_reason varchar(500) DEFAULT NULL COMMENT '变更原因',
  changed_by varchar(64) DEFAULT NULL COMMENT '变更人',
  changed_time datetime DEFAULT NULL COMMENT '变更时间',
  PRIMARY KEY (version_id),
  KEY idx_asset_version_asset (asset_id),
  KEY idx_asset_version_time (changed_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='数据资产版本表';

CREATE TABLE IF NOT EXISTS inf_network_resource (
  network_id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '网络资源ID',
  network_code varchar(64) NOT NULL COMMENT '网络资源编号',
  network_name varchar(128) NOT NULL COMMENT '网络资源名称',
  resource_type varchar(32) NOT NULL COMMENT '资源类型',
  resource_status varchar(32) NOT NULL DEFAULT 'IDLE' COMMENT '资源状态',
  security_status varchar(32) NOT NULL DEFAULT 'NORMAL' COMMENT '安全状态',
  project_id bigint(20) DEFAULT NULL COMMENT '项目ID',
  owner_name varchar(64) DEFAULT NULL COMMENT '责任人',
  ip_segment varchar(128) DEFAULT NULL COMMENT 'IP段',
  ip_count int(11) DEFAULT NULL COMMENT 'IP数量',
  vlan_no varchar(64) DEFAULT NULL COMMENT 'VLAN号',
  bandwidth_mbps int(11) DEFAULT NULL COMMENT '带宽Mbps',
  device_name varchar(128) DEFAULT NULL COMMENT '设备名称',
  device_type varchar(64) DEFAULT NULL COMMENT '设备类型',
  rule_summary text COMMENT '规则摘要',
  access_policy text COMMENT '访问策略',
  topology_doc varchar(255) DEFAULT NULL COMMENT '拓扑文档',
  allocation_doc varchar(255) DEFAULT NULL COMMENT '分配文档',
  monitor_summary varchar(500) DEFAULT NULL COMMENT '监控摘要',
  create_by varchar(64) DEFAULT '' COMMENT '创建者',
  create_time datetime DEFAULT NULL COMMENT '创建时间',
  update_by varchar(64) DEFAULT '' COMMENT '更新者',
  update_time datetime DEFAULT NULL COMMENT '更新时间',
  remark varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (network_id),
  UNIQUE KEY uk_network_code (network_code),
  KEY idx_network_type (resource_type),
  KEY idx_network_status (resource_status),
  KEY idx_network_project (project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='网络资源表';

CREATE TABLE IF NOT EXISTS inf_work_order (
  work_order_id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '工单ID',
  work_order_no varchar(64) NOT NULL COMMENT '工单编号',
  domain_type varchar(32) NOT NULL COMMENT '业务域',
  request_type varchar(32) NOT NULL COMMENT '申请类型',
  order_status varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '工单状态',
  project_id bigint(20) DEFAULT NULL COMMENT '项目ID',
  subject_id bigint(20) DEFAULT NULL COMMENT '主体ID',
  subject_name varchar(128) DEFAULT NULL COMMENT '主体名称',
  subject_type varchar(32) DEFAULT NULL COMMENT '主体类型',
  applicant_dept_id bigint(20) DEFAULT NULL COMMENT '申请部门ID',
  applicant_name varchar(64) DEFAULT NULL COMMENT '申请人',
  approver_name varchar(64) DEFAULT NULL COMMENT '审批人',
  executor_name varchar(64) DEFAULT NULL COMMENT '执行人',
  request_title varchar(128) NOT NULL COMMENT '工单标题',
  request_reason varchar(500) DEFAULT NULL COMMENT '申请原因',
  current_snapshot_json text COMMENT '当前快照',
  request_payload_json text COMMENT '申请内容',
  approval_comment varchar(500) DEFAULT NULL COMMENT '审批意见',
  execution_result varchar(500) DEFAULT NULL COMMENT '执行结果',
  expect_finish_time datetime DEFAULT NULL COMMENT '期望完成时间',
  submitted_time datetime DEFAULT NULL COMMENT '提交时间',
  approved_time datetime DEFAULT NULL COMMENT '审批时间',
  executed_time datetime DEFAULT NULL COMMENT '执行时间',
  create_by varchar(64) DEFAULT '' COMMENT '创建者',
  create_time datetime DEFAULT NULL COMMENT '创建时间',
  update_by varchar(64) DEFAULT '' COMMENT '更新者',
  update_time datetime DEFAULT NULL COMMENT '更新时间',
  remark varchar(500) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (work_order_id),
  UNIQUE KEY uk_work_order_no (work_order_no),
  KEY idx_work_order_domain (domain_type),
  KEY idx_work_order_request (request_type),
  KEY idx_work_order_status (order_status),
  KEY idx_work_order_project (project_id),
  KEY idx_work_order_subject (subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='通用工单表';

SET @menu_max := (SELECT IFNULL(MAX(menu_id), 2000) FROM sys_menu);
SET @info_root := @menu_max + 1;
SET @info_dashboard := @menu_max + 2;
SET @info_project := @menu_max + 3;
SET @info_project_template := @menu_max + 4;
SET @info_project_order := @menu_max + 5;
SET @info_resource := @menu_max + 6;
SET @info_resource_order := @menu_max + 7;
SET @info_application := @menu_max + 8;
SET @info_data_asset := @menu_max + 9;
SET @info_data_order := @menu_max + 10;
SET @info_network := @menu_max + 11;
SET @info_network_order := @menu_max + 12;
SET @btn_start := @menu_max + 20;

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, `query`, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES
(@info_root, '信息化管理', 0, 3, 'information', NULL, '', '', 1, 0, 'M', '0', '0', '', 'chart', 'admin', sysdate(), '', NULL, '信息化管理目录'),
(@info_dashboard, '总览看板', @info_root, 1, 'dashboard', 'information/dashboard/index', '', 'InformationDashboard', 1, 0, 'C', '0', '0', 'information:dashboard:list', 'dashboard', 'admin', sysdate(), '', NULL, '信息化总览'),
(@info_project, '项目管理', @info_root, 2, 'project', 'information/project/index', '', 'InformationProject', 1, 0, 'C', '0', '0', 'information:project:list', 'guide', 'admin', sysdate(), '', NULL, '项目管理'),
(@info_project_template, '项目模板', @info_root, 3, 'projectTemplate', 'information/project/index', '', 'InformationProjectTemplate', 1, 0, 'C', '1', '0', 'information:projectTemplate:list', 'form', 'admin', sysdate(), '', NULL, '项目模板'),
(@info_project_order, '项目验收工单', @info_root, 4, 'projectOrder', 'information/project/index', '', 'InformationProjectOrder', 1, 0, 'C', '1', '0', 'information:projectOrder:list', 'tree', 'admin', sysdate(), '', NULL, '项目验收工单'),
(@info_resource, 'IT资源管理', @info_root, 5, 'resource', 'information/resource/index', '', 'InformationResource', 1, 0, 'C', '0', '0', 'information:resource:list', 'server', 'admin', sysdate(), '', NULL, 'IT资源管理'),
(@info_resource_order, 'IT资源工单', @info_root, 6, 'resourceOrder', 'information/resource/index', '', 'InformationResourceOrder', 1, 0, 'C', '1', '0', 'information:resourceOrder:list', 'time', 'admin', sysdate(), '', NULL, 'IT资源工单'),
(@info_application, '应用管理', @info_root, 7, 'application', 'information/application/index', '', 'InformationApplication', 1, 0, 'C', '0', '0', 'information:application:list', 'monitor', 'admin', sysdate(), '', NULL, '应用管理'),
(@info_data_asset, '数据资源管理', @info_root, 8, 'dataAsset', 'information/dataAsset/index', '', 'InformationDataAsset', 1, 0, 'C', '0', '0', 'information:dataAsset:list', 'example', 'admin', sysdate(), '', NULL, '数据资源管理'),
(@info_data_order, '数据工单', @info_root, 9, 'dataOrder', 'information/dataAsset/index', '', 'InformationDataOrder', 1, 0, 'C', '1', '0', 'information:dataOrder:list', 'edit', 'admin', sysdate(), '', NULL, '数据工单'),
(@info_network, '网络安全管理', @info_root, 10, 'network', 'information/network/index', '', 'InformationNetwork', 1, 0, 'C', '0', '0', 'information:network:list', 'international', 'admin', sysdate(), '', NULL, '网络安全管理'),
(@info_network_order, '网络工单', @info_root, 11, 'networkOrder', 'information/network/index', '', 'InformationNetworkOrder', 1, 0, 'C', '1', '0', 'information:networkOrder:list', 'bug', 'admin', sysdate(), '', NULL, '网络工单');

INSERT INTO sys_menu (menu_id, menu_name, parent_id, order_num, path, component, `query`, route_name, is_frame, is_cache, menu_type, visible, status, perms, icon, create_by, create_time, update_by, update_time, remark) VALUES
(@btn_start + 1, '查询', @info_project, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'information:project:query', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 2, '新增', @info_project, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'information:project:add', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 3, '修改', @info_project, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'information:project:edit', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 4, '删除', @info_project, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'information:project:remove', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 5, '查询', @info_resource, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'information:resource:query', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 6, '新增', @info_resource, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'information:resource:add', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 7, '修改', @info_resource, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'information:resource:edit', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 8, '删除', @info_resource, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'information:resource:remove', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 9, '审批', @info_resource_order, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'information:resourceOrder:approve', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 10, '执行', @info_resource_order, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'information:resourceOrder:execute', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 11, '查询', @info_application, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'information:application:query', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 12, '新增', @info_application, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'information:application:add', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 13, '修改', @info_application, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'information:application:edit', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 14, '删除', @info_application, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'information:application:remove', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 15, '查询', @info_data_asset, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'information:dataAsset:query', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 16, '新增', @info_data_asset, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'information:dataAsset:add', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 17, '修改', @info_data_asset, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'information:dataAsset:edit', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 18, '删除', @info_data_asset, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'information:dataAsset:remove', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 19, '审批', @info_data_order, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'information:dataOrder:approve', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 20, '执行', @info_data_order, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'information:dataOrder:execute', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 21, '查询', @info_network, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'information:network:query', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 22, '新增', @info_network, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'information:network:add', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 23, '修改', @info_network, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'information:network:edit', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 24, '删除', @info_network, 4, '', '', '', '', 1, 0, 'F', '0', '0', 'information:network:remove', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 25, '审批', @info_network_order, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'information:networkOrder:approve', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 26, '执行', @info_network_order, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'information:networkOrder:execute', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 27, '新增', @info_project_template, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'information:projectTemplate:add', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 28, '修改', @info_project_template, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'information:projectTemplate:edit', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 29, '删除', @info_project_template, 3, '', '', '', '', 1, 0, 'F', '0', '0', 'information:projectTemplate:remove', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 30, '审批', @info_project_order, 1, '', '', '', '', 1, 0, 'F', '0', '0', 'information:projectOrder:approve', '#', 'admin', sysdate(), '', NULL, ''),
(@btn_start + 31, '执行', @info_project_order, 2, '', '', '', '', 1, 0, 'F', '0', '0', 'information:projectOrder:execute', '#', 'admin', sysdate(), '', NULL, '');

INSERT INTO sys_role_menu (role_id, menu_id)
SELECT 1, menu_id
FROM sys_menu
WHERE menu_id BETWEEN @info_root AND (@btn_start + 31)
  AND menu_id NOT IN (SELECT menu_id FROM sys_role_menu WHERE role_id = 1);
